repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Keonho Chu
title: Ai Engineer
email: gunho1358@naver.com
website: www.github.com/keonhoChu

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  KeonhoChu
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: __chuuuuoooo
linkedin_username: keonho-chu
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
gtm: "	GTM-MFMCL8L4"
gtag: "G-N33LLK7MJV"
google_analytics: "G-N33LLK7MJV"
# Analytics
analytics:
  provider: "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: "G-N33LLK7MJV"  # Replace with your Google Analytics tracking ID
    anonymize_ip: true  # You can set it to true or false as per your requirement
# About Section
# about_title: About Me
about_profile_image: images/pro1.jpeg
about_content: |  # this will include new lines to allow paragraphs
  Hi, my name's Keonho and I'm a junior Ai Engineer.
  
  I have experience in development and artificial intelligence and am currently in charge of LLM artificial intelligence development in my startup.
  
  I am most skilled in: <img src="https://i.namu.wiki/i/mxMv5lNX8m8lUwu7yTjN6eNZh8JVuI6a_chEyMRc4V9oECkhVIl7OiPiGIOllv14uDVNuwRPVco8abCPe5xOiQ.svg" alt="PYTHON" width="250" height="100">
# content:
#   - title: <mark>Korea Disease Control and Prevention Agency</mark> Project 1
#          # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Infectious Disease Pandemic Outcome Prediction Project
#         link: github.com/sproogen
#         link_text: Project Website
#         additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#           - title:  Github page for project (eg. sproogen/modern-resume-theme)
#             icon: fab fa-github
#             url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: |
#           note : Details are <mark>Confidential</mark> and cannot be disclosed.
          
#         description: | # this will include new lines to allow paragraphs
#          As a project to predict the occurrence of infectious diseases caused by Pendamic, regression analysis was used using <mark>ML</mark> using table data.

content:
  - title: Diclosed Project in KDCA
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Infectious Disease Pandemic Outcome Prediction Project
        description: |
          A project aimed at predicting the occurrence of infectious diseases caused by pandemics using regression analysis and machine learning techniques applied to tabular data.

      - layout: top-middle
        title: Analysis of the frequency of dengue fever among domestic travelers
        description: |
          Investigation into the frequency and spread of dengue fever among domestic travelers to understand the epidemiological dynamics of the disease.

      - layout: top-middle
        title: A predictive program for future norovirus outbreaks based on changes in the timing of norovirus epidemics due to the coronavirus pandemic
        description: |
          Development of a predictive program to anticipate future outbreaks of norovirus by considering the impact of the coronavirus pandemic on the timing and patterns of norovirus epidemics.

      - layout: top-middle
        title: Analysis of Domestic Infectious Disease Statistics Using Foreign Resident Residence Status Data
        description: |
          Examination of domestic infectious disease statistics with a focus on analyzing data related to the residency status of foreign residents to identify potential patterns or correlations.
      - layout: top-middle
        title: Details of all projects carried out by <mark>KDCA</mark> are <mark>Confidential</mark> and cannot be disclosed.  

  - title: Open Projects
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Oral Image Synthesis Data For Artificial Intelligence Learning Project in <mark>SNUDH</mark>
        link:  github.com/KeonhoChu/SNUDH---AI
        link_text: Project Website
        additional_links:
          - title:  KeonhoChu/SNUDH---AI
            icon: fab fa-github
            url: github.com/KeonhoChu/SNUDH---AI
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Award-winning performance: <mark>3rd place</mark>
        description: | # this will include new lines to allow paragraphs
          ![2023 헬스케어 AI 경진대회(포스터](https://raw.githubusercontent.com/bab-korea/healthcare-ai-contest/main/headlthcare_ai_contest_poster.png)
   
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Development of a predictive model for B2B business opportunity creation based on MQL data in <mark>LG</mark>
        link:  github.com/KeonhoChu
        link_text: Project Website
        additional_links:
          - title:  KeonhoChu/SNUDH---AI
            icon: fab fa-github
            url: github.com/KeonhoChu/SNUDH---AI
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Award-winning performance: <mark>final (59th/844)</mark>
        description: | # this will include new lines to allow paragraphs
          ![LG Aimers](https://www.lgresearch.ai/data/upload/image/blog/LG_AI_Research_LG_Aimer_Hackathon_thumbnail_c3d603fc1.png)
  
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: 2024 Digital Heritage Festa AI Heritage Competition Entry Description
        link:  https://github.com/KeonhoChu/National-Heritage-AI-Contest
        link_text: Project Website
        additional_links:
          - title:  KeonhoChu/National-Heritage-AI-Contest
            icon: fab fa-github
            url: github.com/KeonhoChu/National-Heritage-AI-Contest
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          The AI Heritage Contest is a contest that uses AI technology to recreate and reinterpret our national heritage to give it value as a digital heritage and create new content.
        description: | # this will include new lines to allow paragraphs
          ![백제의 영혼](https://raw.githubusercontent.com/KeonhoChu/National-Heritage-AI-Contest/main/%E1%84%87%E1%85%A2%E1%86%A8%E1%84%8C%E1%85%A6%E1%84%8B%E1%85%B4%E1%84%8B%E1%85%A7%E1%86%BC%E1%84%92%E1%85%A9%E1%86%AB.webp)    
 
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Korea Disease Control and Prevention Agency
        # link_text: boringcompany.com
        sub_title: Data Analyst intern
        caption: November 2023 - January 2024
        quote: >
           "Experience is not what happens to you; it's what you do with what happens to you."
        description: | # this will include new lines to allow paragraphs
            As a Data Analyst intern at the Korea Disease Control and Prevention Agency, I was involved in various projects related to data analysis and interpretation. My responsibilities included collecting, cleaning, and analyzing data to identify trends and patterns that could inform public health strategies. I also collaborated with other team members to produce reports and presentations summarizing our findings and recommendations.

      - layout: left
        title: Bionutrion
        link_text: bionutrion.kr
        sub_title: LLM Ai Engineer
        caption: April 2024 - Currently in progress
        quote: >
           "The journey of a thousand miles begins with one step."
        description: |
           Bionutrion is a company developing digital therapeutic devices related to nutrition. As an LLM AI Engineer, my role involves developing and implementing machine learning algorithms to analyze nutritional data and provide personalized recommendations for users. I work closely with a multidisciplinary team to design and optimize algorithms that improve the effectiveness of our digital therapeutic solutions.
    
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Konkuk University  
        caption: March 2015 - February 2021
        sub_title: BS Biomedical Engineering 
        quote: >
           "Education is the passport to the future, for tomorrow belongs to those who prepare for it today."
        description: | # this will include new lines to allow paragraphs
           My undergraduate studies at Konkuk University focused on Biomedical Engineering, where I gained knowledge in various areas such as biology, chemistry, and engineering principles applied to medical devices and systems. Through coursework, projects, and internships, I developed skills in data analysis, problem-solving, and interdisciplinary collaboration, preparing me for a career in the healthcare industry.
    
      - layout: left
        title: Completion of S/W development and application expert training using medical bio-AI (KDT)
        caption: February 2023 - July 2023
        sub_title: Linked to Chungbuk National University Hospital
        quote: >
            "Continuous learning is the key to unlocking your full potential."
        description: |
            During the S/W development and application expert training using medical bio-AI (KDT) program, I acquired advanced skills in software development and applications, specifically focused on medical bioinformatics and artificial intelligence. The program, linked to Chungbuk National University Hospital, provided hands-on training and practical experience in developing software solutions for medical data analysis and interpretation. Through this intensive training, I enhanced my understanding of medical informatics and AI technologies, preparing me to contribute effectively to healthcare innovation.

    
      - layout: left
        title: Completion of the Tableau boot camp
        caption: October 2023 - November 2023
        sub_title: Tableau
        quote: >
           "Success is not final, failure is not fatal: It is the courage to continue that counts."
        description: |
           The completion of the Tableau boot camp in 2023 provided me with comprehensive training in Tableau, a powerful data visualization tool. During this intensive program, I gained practical experience in creating interactive dashboards, designing insightful visualizations, and interpreting data to drive business decisions. Through hands-on projects and exercises, I developed proficiency in using Tableau to analyze complex datasets and communicate findings effectively to stakeholders.

    
      - layout: left
        title: LG Aimers/Data Intelligence
        caption: January 2024 - February 2024
        sub_title: LG AI researcher
        quote: >
           "Innovation distinguishes between a leader and a follower."
        description: |
            During my time at LG Aimers/Data Intelligence as an AI researcher, I was involved in cutting-edge research and development projects focused on advancing artificial intelligence technologies. My responsibilities included conducting experiments, analyzing data, and developing algorithms to enhance the performance of AI systems. I collaborated closely with multidisciplinary teams to explore new ideas, solve complex problems, and deliver innovative solutions that meet the needs of LG's customers and stakeholders.
 
  - title: Certificate
    layout: list
    content:
      - layout: left
        border: weak
        title: KT - Aice
        sub_title: Date of acquisition
        caption: 2023-10-28
        quote: >
          Certificate Issuing Authority: <mark>KT</mark>
        description: |
          <div style="width: 50%; margin: 0 auto;">
            <img src="https://img.hankyung.com/photo/202307/AA.33883746.1.jpg" alt="kt aice" style="width: 50%;">
          </div>
      - layout: left
        border: weak
        title: Azure AI Fundamentals AI-900
        sub_title: Date of acquisition
        caption: 2023-07-14
        quote: >
          Certificate Issuing Authority: <mark>Microsoft</mark>
        description: |
          <div style="width: 50%; margin: 0 auto;">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTU3cSI_Dsx2pWlonpWJpbwUC-Eg44Y-FO1wGGTZKd1Hg&s" alt="azure" style="width: 50%;">
          </div>
      - layout: left
        border: weak
        title: ADSP (Advanced Data Analytics Semi-Professional)
        sub_title: Date of acquisition
        caption: 2023-06-19
        quote: >
          Certificate Issuing Authority: <mark>Korea Data Agency</mark>
        description: |
          <div style="width: 50%; margin: 0 auto;">
            <img src="https://velog.velcdn.com/images/zinu/post/313d9059-6d4e-4371-a386-aa068d478aa6/image.png" alt="adsp" style="width: 50%;">
          </div>
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AI engineering some of my other interests and hobbies are:
      - Stock trading : Tesla, Nvidia, Intel etc...
      - Gaming : LostArk, League of Legends, Battleground etc...
      - Participation In the Festival 
      - ESG : Save Earth! 
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
